name: Build Boxes
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  build-linux-box:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set ENV Variables
        run: |
          for v in `cat .env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Packer Build
        run: |
          packer build linux.json
      - name: Upload Box To Artifacts 
        uses: actions/upload-artifact@v2
        with:
          name: box
          path: output-vagrant/package.box
