name: "Build Boxes"
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  build-linux-box:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set ENV Variables
        run: |
          for v in `cat .env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Run Packer Build
        run: |
          PACKER_LOG=1 packer build linux.json