name: Build Boxes
on:
  push:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  build-ubuntu-box:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set ENV Variables
        run: |
          for v in `cat .env` ; do echo "::set-env name=${v%%=*}::${v##*=}" ; done
      - name: Packer Build
        run: |
          packer build ubuntu.json
      - name: Upload Box To S3 Bucket
        run: |
          aws s3 cp output-vagrant/package.box s3://packer-ubuntu-dev-box-ajkayalan/package.box
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
